bg_image = ""
category = "projet"
description = "bla-bla projet"
image = ""
information = []
title = "Essai_nouveau_projet"
_1- L’œuvre architecturale doit être originale pour être protégée par le droit d’auteur_

Les œuvres architecturales ont pour particularités que l’architecte ne peut créer librement. Il est souvent contraint par _« les demandes du maître d’ouvrage et les fonctions de l’ouvrage »_.

Néanmoins, les plans d’architecte, les croquis, les maquettes, mais également les édifices conçus par l’architecte sont protégés par le droit d’auteur, dès lors qu’ils présentent un caractère original (Cass. 1e civ. 6 mars 1979, SARL Le Mas Provençal / Carlier ; Cass., 1ère civ., 12 novembre 1980, n° 79-13.544).

L’originalité est appréciée souverainement par les juges du fond. Ainsi, il a été reconnu deux critères pour déterminer l’originalité d’un bâtiment :   
![-](https://www.village-justice.com/articles/local/cache-vignettes/L8xH11/puce-32883.gif?1589621704 =8x11) _« un caractère artistique certain »_, c’est-à-dire, lorsque l’architecte auteur crée des formes particulières, quel qu’en soit le mérite ou le caractère esthétique, _« distinctes des nécessités techniques »_,   
![-](https://www.village-justice.com/articles/local/cache-vignettes/L8xH11/puce-32883.gif?1589621704 =8x11) et « _le fait qu’il ne s’agisse pas d’une construction en série_ » (CA Riom 26 mai 1967).

En somme, une œuvre est protégée dès lors qu’elle porte l’empreinte de la personnalité de son auteur.

**2- Les droits patrimoniaux et le droit moral de l’architecte sur son œuvre originale**

L’architecte a des droits patrimoniaux en vertu desquels il est seul habilité à autoriser la fabrication et l’exploitation de son œuvre et de l’image de cette dernière.

En effet, aux termes de l’article L. 111-1 du Code de la propriété intellectuelle, l’architecte jouit sur son œuvre, du seul fait de sa création, d’un droit de propriété incorporelle exclusif et opposable à tous. Ce droit comporte des attributs d’ordre intellectuel et moral ainsi que des attributs d’ordre patrimonial.

En vertu de son droit moral, l’architecte dispose d’un droit au respect de son œuvre et d’un droit de paternité (article L. 121-1 du Code susvisé _« l’auteur jouit du droit au respect de son nom, de sa qualité (...) »_).

Ainsi, il est seul, en sa qualité d’architecte auteur, à pouvoir décider de la divulgation, de la modification ou l’adaptation de son œuvre et son nom doit être mentionné sur tout plan, toute étude ou tout bâtiment, qui est original.

Le droit moral de l’architecte auteur s’exerce dans les rapports avec les maîtres de l’ouvrage.

Toutefois, l’architecte peut se trouver confronter à la problématique suivante :